# Generated by Django 4.1.5 on 2023-01-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdetails', '0003_rename_password_details_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Pinno',
            new_name='Fristname',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='Lastname',
        ),
        migrations.AddField(
            model_name='details',
            name='Pin_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
